file_path: /lustre/ssd/ws/dchristi-3dseg/data/RAW-Volumen-Wohlfahrt/C3-H81_3cm-oben-raw_subvolume2.h5
result_path: /lustre/ssd/ws/dchristi-3dseg/str-tensor_results/
dtype: np.uint16
fiber_diameter: 7 
voxel_size: 7.5
# path to the raw data within the H5
raw_internal_path: /raw