file_path: data/original/285_01_HR_.vol.sub.h5
raw_internal_path: /volume
block_size: [32,32,32]
out_path: results/test/285_01_HR_.vol.vec.test.sub.h5
fiber_diameter: 7.e-3 
voxel_size: 0.00230760

# path to the raw data within the H5
